workflows:
  build-ios:
    name: Build iOS for Farman Jardi
    environment:
      xcode: 15.0
    scripts:
      - name: Build iOS .ipa
        script: |
          xcodebuild -project "Unity-iPhone.xcodeproj" \
          -scheme "Unity-iPhone" \
          -configuration Release \
          -archivePath "$HOME/build/farmanjardi.xcarchive" archive

          xcodebuild -exportArchive \
          -archivePath "$HOME/build/farmanjardi.xcarchive" \
          -exportOptionsPlist exportOptions.plist \
          -exportPath "$HOME/build/ipa"
    artifacts:
      - build/ipa/*.ipa
